[package]
name = "sad"
version = "0.3.3"
description = "Space Age seD | https://github.com/ms-jpq/sad"
authors = ["git@bigly.dog"]
edition = "2018"


[dependencies]
futures = "0.3"
structopt = "0.3"
tokio = { version = "0.2", features = ["fs", "io-std", "io-util", "process", "sync", "rt-threaded"] }
async-std = { version = "1.6", features = ["unstable"] }
num_cpus = "1"
regex = "1"
aho-corasick = "0.7"
difflib = "0.4"
uuid = { version = "0.8", features = ["v4"] }
ansi_term = "0.12"
atty = "0.2"
which = "3"
